{
 "title": "real-time-dashboard Copy",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "stock",
    "label": "stock",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(bucket: \"primary\", tag: \"stock\")"
   },
   {
    "name": "start",
    "label": "start",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume ${stock}",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"primary\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stock-price-v1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume\" )\r\n  |> filter(fn: (r) => r[\"stock\"] == \"${stock:regex}\")"
    }
   ]
  },
  {
   "title": "Open",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"primary\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stock-price-v1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume\")\r\n  |> filter(fn: (r) => r[\"stock\"] == \"AMZN\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Heigh",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "\r\n\r\nfrom(bucket: \"primary\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stock-price-v1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"high\" )\r\n  |> filter(fn: (r) => r[\"stock\"] == \"${stock:regex}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"primary\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume\")\r\n  |> filter(fn: (r) => r[\"stock\"] == \"${stock:regex}\")"
    }
   ]
  },
  {
   "title": "close",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"primary\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stock-price-v1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volume\")\r\n  |> filter(fn: (r) => r[\"stock\"] == \"AMZN\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "query": "\r\n\r\nfrom(bucket: \"primary\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stock-price-v1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"low\" )\r\n  |> filter(fn: (r) => r[\"stock\"] == \"${stock:regex}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "${stock} candlestick",
   "type": "candlestick",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"primary\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stock-price-v1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"close\" or r[\"_field\"] == \"high\" or r[\"_field\"] == \"low\" or r[\"_field\"] == \"open\" or r[\"_field\"] == \"volume\")\r\n  |> filter(fn: (r) => r[\"stock\"] == \"${stock:regex}\")"
    }
   ]
  },
  {
   "title": "Stock prices ${stock}",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"primary\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stock-price-v1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"close\")\r\n  |> filter(fn: (r) => r[\"stock\"] == \"${stock:regex}\")"
    }
   ]
  }
 ]
}